title: LeetCode solutions by tgic
email: farmer1992@gmail.com
description: "LeetCode java solutions by tgic"
github_username:  tg123
markdown: redcarpet

baseurl: ""
url: "http://leetcode.tgic.me/"

redcarpet:
  extensions: ['highlight', 'autolink']

highlighter: pygments
